ContainerDefinitions:
  - ContainerDefinition
Cpu: String
ExecutionRoleArn: String
Family: String
Memory: String
NetworkMode: String
RequiresCompatibilities:
  - String
Tags:
  - Tag
TaskRoleArn: String
Volumes:
  - Volume
