containerDefinitions:
- logConfiguration:
    logDriver: awslogs
    secretOptions:
    options:
      awslogs-group: dash
      awslogs-region: us-east-1
      awslogs-stream-prefix: dash/app
  entryPoint:
  portMappings:
  - hostPort: 3000
    protocol: tcp
    containerPort: 3000
  command:
  - rails
  - staging
  cpu: 0
  environment:
  - name: APPLICATION_DOMAIN
    value: track2883.testing.siftery.com
  - name: AUTH_PROXY_DOMAIN
    value: https://auth-proxy.testing.siftery.com/users/auth/google/callback
  - name: AV_HOSTNAME
    value: av.dash.testing
  - name: DB_HOST
    value: dash-testing.cdcqpkmeyjz2.us-east-1.rds.amazonaws.com
  - name: DB_NAME
    value: dash_stg2
  - name: ENABLE_NR
    value: 'false'
  - name: JOB_WORKER_URL
    value: redis://127.0.0.1:6379/0
  - name: RAILS_ENV
    value: staging
  mountPoints:
  - readOnly:
    containerPath: "/opt/dash"
    sourceVolume: app
  - readOnly:
    containerPath: "/opt/dash/log/custom_upload_files"
    sourceVolume: app_data
  memory:
  memoryReservation: 128
  stopTimeout: 30
  image: '002417289773.dkr.ecr.us-east-1.amazonaws.com/dash-test:dev-lubdhak_workspace_injector_fix'
  startTimeout: 30
  dependsOn:
  healthCheck:
  essential: true
  name: app

memory: '16384'
taskRoleArn: arn:aws:iam::002417289773:role/dash_ecs_staging
executionRoleArn: arn:aws:iam::002417289773:role/dash_ecs_staging
taskDefinitionArn: arn:aws:ecs:us-east-1:002417289773:task-definition/testing_dash_stack:363
family: testing_yantra
requiresCompatibilities:
- FARGATE
networkMode: awsvpc
cpu: '4096'
volumes:
- name: app_data
- name: app
