---
Cluster: dash-testing
Count: 1
EnableECSManagedTags: false
LaunchType: FARGATE
NetworkConfiguration:
  AwsVpcConfiguration:
    AssignPublicIp:
    SecurityGroups:
      - sg-07533be05931b6f51
    Subnets:
      - subnet-0a41be75ba2fb9c6f
PlatformVersion: 1.3.0

---
Image:
  AppProd: 002417289773.dkr.ecr.us-east-1.amazonaws.com/dash-prod
  AppDev: 002417289773.dkr.ecr.us-east-1.amazonaws.com/dash-test
  Web: 002417289773.dkr.ecr.us-east-1.amazonaws.com/dash-web

Route53:
  HostedZone: Z2VPLB83J447ZF
  DomainSuffix: .testing.siftery.com
  DomainPrefix: track

Environment:
  DatabaseName:
