before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: saurabhjambhule
    name: yantra
  draft: true
  prerelease: auto
  header: |
    Welcome to this new release!

  footer: |
    Thanks!

brews:
  - tap:
      owner: saurabhjambhule
      name: yantra
    name: yantra
    description: "An automation engine for building platform services."
    homepage: "https://github.com/saurabhjambhule/yantra"
    license: "Apache 2.0"
    folder: Formula
    commit_author:
      name: Saurabh Jambhule
      email: saurabhjambhule@gmail.com
    install: bin.install "yantra"
    test: |
      system "#{bin/yantra}"
