site_name: yantra
site_url: https://saurabhjambhule.github.io/yantra/
site_description: An automation engine for building platform services.
repo_name: saurabhjambhule/yantra
repo_url: https://github.com/saurabhjambhule/yantra
edit_uri: edit/main/docs/docs/

theme:
  name: material
  language: en
  include_search_page: false
  search_index_only: true
  features:
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme: light)"  # Light mode
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"  # Dark mode
      scheme: slate
      primary: light blue
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
