name: docs
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependecies
        run: pip install mkdocs-material

      - name: Publish docs
        run: |
          cd docs
          mkdocs gh-deploy --force
